/usr/local/openresty/nginx/logs/*.log {
    daily
    missingok
    rotate 15
    compress
    nodelaycompress
    notifempty
    olddir ./backup
    create 0644 root root
    dateext

    sharedscripts
    postrotate
        if [ -f /usr/local/openresty/nginx/logs/nginx.pid ]; then
            kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid`
        else
            MASTER_PID=$(pgrep -P 1 nginx | head -n 1)
            if [ -n "$MASTER_PID" ]; then
                kill -USR1 $MASTER_PID
            fi
        fi
    endscript
}